import type { ArtifactDef, TargetOs, ImplStatus } from "@eec/schema";

// Compact constructor so every entry still carries the full contract (see ArtifactDef).
type Seed = Partial<ArtifactDef> & Pick<ArtifactDef, "id" | "name" | "category" | "os" | "description" | "sources" | "output">;

const ALL_UNVERIFIED = (os: TargetOs[]): Partial<Record<TargetOs, ImplStatus>> =>
  Object.fromEntries(os.map((o) => [o, "implemented-unverified" as ImplStatus]));

function a(s: Seed): ArtifactDef {
  return {
    aliases: [], group: s.category, versionConstraints: "Not yet validated against specific OS versions.",
    discovery: "Fixed, catalog-defined path or command.", userScope: "machine-wide", privilege: "none",
    sensitivity: "low", acquisition: "copy", acquisitionDetail: "Read-only copy.", timeFilter: "none",
    timeFilterNote: "No time filter: the whole source is acquired (bounded by size limits).",
    dependsOn: [], failureModes: ["Source missing", "Access denied"], fixtures: [], references: [],
    status: ALL_UNVERIFIED(s.os),
    ...s,
  };
}

const WIN_EVT = "https://learn.microsoft.com/windows/win32/eventlog/event-logging";
const WIN_SCHTASK = "https://learn.microsoft.com/windows/win32/taskschd/task-scheduler-start-page";
const MAC_LAUNCHD = "https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html";
const MAC_PRIV = "https://support.apple.com/guide/security/controlling-app-access-to-files-secddd1d86a6/web";
const LINUX_JOURNAL = "https://www.freedesktop.org/software/systemd/man/latest/journalctl.html";

export const ARTIFACTS: ArtifactDef[] = [
  // ---------------- Windows ----------------
  a({ id: "win.baseline.system", name: "System baseline", category: "baseline", os: ["windows"], aliases: ["system info", "os version"],
    description: "OS version, hostname, uptime, execution identity, elevation state, installed hotfix list.",
    sources: ["Get-CimInstance Win32_OperatingSystem", "Get-CimInstance Win32_ComputerSystem", "whoami /all (identity only, no secrets)"],
    acquisition: "snapshot", acquisitionDetail: "PowerShell CIM queries written as JSON.", output: "baseline/system.json", fixtures: ["tests/fixtures/win/baseline.json"] }),
  a({ id: "win.volatile.processes", name: "Process list", category: "volatile", os: ["windows"], aliases: ["running processes", "tasklist"],
    description: "Process name, PID, parent PID, path and start time. Command lines are a separate sensitive option.",
    sources: ["Get-CimInstance Win32_Process (without CommandLine)"], acquisition: "snapshot", output: "volatile/processes.json", group: "volatile:processes" }),
  a({ id: "win.volatile.processes.cmdline", name: "Process command lines", category: "volatile", os: ["windows"], aliases: ["command line", "cmdline"],
    description: "Command-line arguments for running processes. Can contain secrets such as tokens or passwords.",
    sources: ["Get-CimInstance Win32_Process (CommandLine)"], acquisition: "snapshot", sensitivity: "sensitive-option", dependsOn: ["win.volatile.processes"],
    output: "volatile/process-cmdlines.json", group: "volatile:cmdline", selectAllExcluded: true }),
  a({ id: "win.volatile.network", name: "Network connections", category: "volatile", os: ["windows"], aliases: ["netstat", "tcp", "listening"],
    description: "TCP connections and listening ports with owning PID; UDP endpoints; DNS client cache is not collected.",
    sources: ["Get-NetTCPConnection", "Get-NetUDPEndpoint"], acquisition: "snapshot", output: "volatile/network.json", group: "volatile:network" }),
  a({ id: "win.logs.security", name: "Security event log", category: "logs", os: ["windows"], aliases: ["security evtx", "4624", "logon events"],
    description: "Security.evtx exported by the Windows event log API within the time window.",
    sources: ["wevtutil epl Security (query filtered by time)"], acquisition: "export", privilege: "elevated-required", sensitivity: "moderate",
    timeFilter: "native", timeFilterNote: "Time window applied natively via an event-query XPath filter.",
    failureModes: ["Access denied without elevation", "Log cleared/rolled over"], output: "logs/Security.evtx", references: [WIN_EVT], group: "logs:eventlogs" }),
  a({ id: "win.logs.system", name: "System event log", category: "logs", os: ["windows"], aliases: ["system evtx"],
    description: "System.evtx exported within the time window.", sources: ["wevtutil epl System"], acquisition: "export", privilege: "elevated-recommended",
    timeFilter: "native", timeFilterNote: "Native time filter via event query.", output: "logs/System.evtx", references: [WIN_EVT], group: "logs:eventlogs" }),
  a({ id: "win.logs.application", name: "Application event log", category: "logs", os: ["windows"], aliases: ["application evtx"],
    description: "Application.evtx exported within the time window.", sources: ["wevtutil epl Application"], acquisition: "export",
    timeFilter: "native", timeFilterNote: "Native time filter via event query.", output: "logs/Application.evtx", references: [WIN_EVT], group: "logs:eventlogs" }),
  a({ id: "win.logs.powershell", name: "PowerShell operational log", category: "logs", os: ["windows"], aliases: ["powershell evtx", "script block"],
    description: "Microsoft-Windows-PowerShell/Operational if present. Not enabled on all systems; the collector does not enable it.",
    sources: ["wevtutil epl Microsoft-Windows-PowerShell/Operational"], acquisition: "export", sensitivity: "moderate",
    timeFilter: "native", timeFilterNote: "Native time filter.", failureModes: ["Channel disabled or empty"], output: "logs/PowerShell-Operational.evtx", group: "logs:eventlogs" }),
  a({ id: "win.scheduled.tasks", name: "Scheduled task definitions", category: "scheduled", os: ["windows"], aliases: ["schtasks", "task scheduler", "scheduled tasks"],
    description: "XML definitions of registered scheduled tasks.", sources: ["Get-ScheduledTask | Export-ScheduledTask"], acquisition: "export",
    privilege: "elevated-recommended", output: "scheduled/tasks/", references: [WIN_SCHTASK], failureModes: ["Tasks hidden from non-elevated users"] }),
  a({ id: "win.scheduled.history", name: "Scheduled task history", category: "scheduled", os: ["windows"], aliases: ["task history"],
    description: "Microsoft-Windows-TaskScheduler/Operational events, if the channel is enabled.", sources: ["wevtutil epl Microsoft-Windows-TaskScheduler/Operational"],
    acquisition: "export", timeFilter: "native", timeFilterNote: "Native time filter.", failureModes: ["History disabled by default on many systems"], output: "scheduled/TaskScheduler-Operational.evtx" }),
  a({ id: "win.persistence.services", name: "Services", category: "persistence", os: ["windows"], aliases: ["service config"],
    description: "Service name, display name, state, start mode, binary path and account.", sources: ["Get-CimInstance Win32_Service"], acquisition: "snapshot", output: "persistence/services.json" }),
  a({ id: "win.persistence.startup", name: "Startup folders", category: "persistence", os: ["windows"], aliases: ["startup folder"],
    description: "Listing and metadata of all-users and per-user Startup folder entries (metadata only, files not copied).",
    sources: ["%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup", "<profile>\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"],
    acquisition: "metadata", userScope: "per-user", output: "persistence/startup-folders.json" }),
  a({ id: "win.registry.autoruns", name: "Autorun registry keys", category: "registry", os: ["windows"], aliases: ["run keys", "runonce"],
    description: "Run/RunOnce keys under HKLM and each loaded/loadable user hive.", acquisition: "export", userScope: "per-user", privilege: "elevated-recommended",
    sources: ["HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", "HKLM\\...\\RunOnce", "HKU\\<sid>\\...\\Run (loaded hives only)"],
    failureModes: ["Unloaded user hives are reported unavailable; collector does not load them without approval"], output: "registry/autoruns.json" }),
  a({ id: "win.registry.services", name: "Services registry key", category: "registry", os: ["windows"], aliases: ["services key"],
    description: "HKLM\\SYSTEM\\CurrentControlSet\\Services values (names, ImagePath, Start, ObjectName).", sources: ["HKLM\\SYSTEM\\CurrentControlSet\\Services"],
    acquisition: "export", output: "registry/services.json" }),
  a({ id: "win.registry.broad", name: "Broader registry hive export", category: "registry", os: ["windows"], aliases: ["hive export", "full registry"],
    description: "Optional: reg export of selected hive branches. Large; requires elevation. Credential hives (SAM/SECURITY) are NEVER collected.",
    sources: ["reg export HKLM\\SOFTWARE", "reg export HKLM\\SYSTEM"], acquisition: "export", privilege: "elevated-required", sensitivity: "moderate",
    failureModes: ["Large output hits per-file limit"], output: "registry/hklm-software.reg", status: { windows: "planned" }, selectAllExcluded: true, group: "registry:broad" }),
  a({ id: "win.browser.chromium.history", name: "Chromium history & downloads", category: "browser", os: ["windows"], aliases: ["chrome history", "edge history", "brave history", "downloads"],
    description: "History database for Chrome, Edge and Brave per user per profile. Includes visited URLs and downloads (personal data).",
    sources: ["<profile>\\AppData\\Local\\Google\\Chrome\\User Data\\<Profile>\\History", "...\\Microsoft\\Edge\\User Data\\<Profile>\\History", "...\\BraveSoftware\\Brave-Browser\\User Data\\<Profile>\\History"],
    discovery: "Enumerate user profiles, then each 'Default' and 'Profile N' directory under the browser's User Data directory.",
    userScope: "per-user-profile", sensitivity: "personal-data", acquisition: "copy", acquisitionDetail: "SQLite DB copied with -wal/-journal siblings; marked as live copy.",
    failureModes: ["Database locked by running browser", "Profile unreadable"], output: "browser/<user>/<browser>/<profile>/History", group: "browser:history" }),
  a({ id: "win.browser.chromium.config", name: "Chromium extensions & preferences", category: "browser", os: ["windows"], aliases: ["chrome extensions", "edge extensions"],
    description: "Extension manifests and the Preferences file. Cookies, Login Data and Web Data are NOT collected.", sources: ["<profile>\\...\\User Data\\<Profile>\\Preferences", "...\\Extensions\\<id>\\<ver>\\manifest.json"],
    userScope: "per-user-profile", sensitivity: "moderate", output: "browser/<user>/<browser>/<profile>/config/", group: "browser:config" }),
  a({ id: "win.browser.firefox.history", name: "Firefox history & downloads", category: "browser", os: ["windows"], aliases: ["firefox places"],
    description: "places.sqlite for each Firefox profile.", sources: ["<profile>\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\<name>\\places.sqlite"],
    discovery: "Enumerate profile directories listed under Firefox\\Profiles.", userScope: "per-user-profile", sensitivity: "personal-data",
    acquisitionDetail: "SQLite DB copied with -wal sibling; marked live copy.", failureModes: ["Locked database"], output: "browser/<user>/firefox/<profile>/places.sqlite", group: "browser:history" }),
  a({ id: "win.browser.firefox.config", name: "Firefox extensions & prefs", category: "browser", os: ["windows"], aliases: ["firefox addons"],
    description: "extensions.json and prefs.js. key4.db / logins.json / cookies.sqlite are NOT collected.", sources: ["<profile>\\...\\Firefox\\Profiles\\<name>\\extensions.json", "...\\prefs.js"],
    userScope: "per-user-profile", sensitivity: "moderate", output: "browser/<user>/firefox/<profile>/config/", group: "browser:config" }),
  a({ id: "win.userlogs.temp", name: "Installer & CBS logs", category: "userlogs", os: ["windows"], aliases: ["cbs log", "setupapi"],
    description: "Selected existing logs: C:\\Windows\\Logs\\CBS\\CBS.log, C:\\Windows\\INF\\setupapi.dev.log.", sources: ["C:\\Windows\\Logs\\CBS\\CBS.log", "C:\\Windows\\INF\\setupapi.dev.log"],
    sensitivity: "low", output: "userlogs/" }),

  // ---------------- macOS ----------------
  a({ id: "mac.baseline.system", name: "System baseline", category: "baseline", os: ["macos"], aliases: ["sw_vers", "system info"],
    description: "OS version, hostname, uptime, execution identity and elevation state.", sources: ["sw_vers", "uname -a", "uptime", "id"], acquisition: "snapshot", output: "baseline/system.txt" }),
  a({ id: "mac.volatile.processes", name: "Process list", category: "volatile", os: ["macos"], aliases: ["ps"],
    description: "PID, PPID, user, start time and executable name. Command lines are a separate sensitive option.", sources: ["ps -axo pid,ppid,user,lstart,comm"], acquisition: "snapshot", output: "volatile/processes.txt", group: "volatile:processes" }),
  a({ id: "mac.volatile.processes.cmdline", name: "Process command lines", category: "volatile", os: ["macos"], aliases: ["command line", "cmdline"],
    description: "Full command-line arguments; may contain secrets.", sources: ["ps -axo pid,args"], acquisition: "snapshot", sensitivity: "sensitive-option", dependsOn: ["mac.volatile.processes"],
    output: "volatile/process-cmdlines.txt", group: "volatile:cmdline", selectAllExcluded: true }),
  a({ id: "mac.volatile.network", name: "Network connections", category: "volatile", os: ["macos"], aliases: ["netstat", "lsof network"],
    description: "Listening and established sockets.", sources: ["netstat -anv", "lsof -nP -i (limited)"], acquisition: "snapshot", privilege: "elevated-recommended",
    failureModes: ["Non-root sees only own sockets in lsof"], output: "volatile/network.txt", group: "volatile:network" }),
  a({ id: "mac.logs.unified", name: "Unified log (bounded export)", category: "logs", os: ["macos"], aliases: ["log show", "unified logging", "oslog"],
    description: "Bounded 'log show' export for the time window, predicate limited to process launch/auth subsystems. Not a logarchive.",
    sources: ["log show --style ndjson --start <t> --end <t> --predicate '<fixed predicate>'"], acquisition: "export", privilege: "elevated-required",
    timeFilter: "native", timeFilterNote: "Native --start/--end filtering.", sensitivity: "moderate", failureModes: ["Requires root", "Large output hits limit; reported partial"],
    output: "logs/unified.ndjson", references: ["man log"], group: "logs:system" }),
  a({ id: "mac.logs.system", name: "/var/log system logs", category: "logs", os: ["macos"], aliases: ["system.log", "install.log"],
    description: "install.log and system.log (if present) from /var/log.", sources: ["/var/log/install.log", "/var/log/system.log"], privilege: "elevated-recommended",
    timeFilter: "none", output: "logs/var-log/", group: "logs:system" }),
  a({ id: "mac.scheduled.cron", name: "Cron configuration", category: "scheduled", os: ["macos"], aliases: ["crontab", "cron"],
    description: "System and user crontabs and at jobs where readable.", sources: ["/etc/crontab", "/usr/lib/cron/tabs/<user>", "/private/var/at"], privilege: "elevated-recommended",
    userScope: "per-user", failureModes: ["Privacy controls may block reads"], output: "scheduled/cron/" }),
  a({ id: "mac.scheduled.launchd", name: "launchd jobs (agents & daemons)", category: "scheduled", os: ["macos"], aliases: ["launch agents", "launch daemons", "plist", "launchd"],
    description: "Plist definitions that schedule or auto-start jobs (also see Startup).",
    sources: ["/Library/LaunchAgents", "/Library/LaunchDaemons", "/System/Library/LaunchAgents (listing)", "<home>/Library/LaunchAgents"],
    userScope: "per-user", acquisitionDetail: "Plist files copied as-is; not parsed or executed.", references: [MAC_LAUNCHD], output: "scheduled/launchd/" }),
  a({ id: "mac.persistence.launchd", name: "Startup & login items", category: "persistence", os: ["macos"], aliases: ["login items", "startup items", "startup"],
    description: "Metadata for launchd persistence directories and legacy StartupItems; background-task-management database is NOT copied.",
    sources: ["/Library/StartupItems", "/etc/rc.common", "launchctl list (snapshot)"], acquisition: "metadata", output: "persistence/startup.json", references: [MAC_LAUNCHD] }),
  a({ id: "mac.browser.safari.history", name: "Safari history & downloads", category: "browser", os: ["macos"], aliases: ["safari"],
    description: "History.db and Downloads.plist where readable. Requires Full Disk Access granted by the organization to the executing process; the collector never grants it.",
    sources: ["<home>/Library/Safari/History.db", "<home>/Library/Safari/Downloads.plist"], userScope: "per-user", sensitivity: "personal-data",
    failureModes: ["Blocked by macOS privacy controls (TCC) without Full Disk Access", "Locked DB"], output: "browser/<user>/safari/", group: "browser:history", references: [MAC_PRIV],
    status: { macos: "implemented-unverified" } }),
  a({ id: "mac.browser.chromium.history", name: "Chromium history & downloads", category: "browser", os: ["macos"], aliases: ["chrome history", "edge history", "brave history", "downloads"],
    description: "History DB for Chrome/Edge/Brave per user per profile.", sources: ["<home>/Library/Application Support/Google/Chrome/<Profile>/History", "…/Microsoft Edge/<Profile>/History", "…/BraveSoftware/Brave-Browser/<Profile>/History"],
    userScope: "per-user-profile", sensitivity: "personal-data", acquisitionDetail: "SQLite DB copied with -wal/-journal; live copy.", failureModes: ["Locked DB", "TCC restrictions"],
    output: "browser/<user>/<browser>/<profile>/History", group: "browser:history" }),
  a({ id: "mac.browser.chromium.config", name: "Chromium extensions & preferences", category: "browser", os: ["macos"], aliases: ["chrome extensions"],
    description: "Preferences and extension manifests. No cookies / Login Data.", sources: ["<home>/Library/Application Support/Google/Chrome/<Profile>/Preferences", "…/Extensions/<id>/<ver>/manifest.json"],
    userScope: "per-user-profile", sensitivity: "moderate", output: "browser/<user>/<browser>/<profile>/config/", group: "browser:config" }),
  a({ id: "mac.browser.firefox.history", name: "Firefox history & downloads", category: "browser", os: ["macos"], aliases: ["firefox places"],
    description: "places.sqlite per Firefox profile.", sources: ["<home>/Library/Application Support/Firefox/Profiles/<name>/places.sqlite"], userScope: "per-user-profile",
    sensitivity: "personal-data", output: "browser/<user>/firefox/<profile>/places.sqlite", group: "browser:history" }),
  a({ id: "mac.browser.firefox.config", name: "Firefox extensions & prefs", category: "browser", os: ["macos"], aliases: ["firefox addons"],
    description: "extensions.json and prefs.js. No logins/cookies.", sources: ["<home>/Library/Application Support/Firefox/Profiles/<name>/extensions.json", "…/prefs.js"],
    userScope: "per-user-profile", sensitivity: "moderate", output: "browser/<user>/firefox/<profile>/config/", group: "browser:config" }),
  a({ id: "mac.userlogs.user", name: "User Library logs", category: "userlogs", os: ["macos"], aliases: ["~/Library/Logs", "crash reports", "diagnostic reports"],
    description: "Existing files under <home>/Library/Logs (top two levels, size bounded).", sources: ["<home>/Library/Logs"], userScope: "per-user", sensitivity: "moderate",
    failureModes: ["TCC restrictions"], output: "userlogs/<user>/" }),

  // ---------------- Linux ----------------
  a({ id: "lin.baseline.system", name: "System baseline", category: "baseline", os: ["linux"], aliases: ["os-release", "uname"],
    description: "OS release, kernel, hostname, uptime, execution identity.", sources: ["/etc/os-release", "uname -a", "uptime", "id"], acquisition: "snapshot", output: "baseline/system.txt" }),
  a({ id: "lin.volatile.processes", name: "Process list", category: "volatile", os: ["linux"], aliases: ["ps"],
    description: "PID, PPID, user, start time, executable name (no arguments).", sources: ["ps -eo pid,ppid,user,lstart,comm"], acquisition: "snapshot", output: "volatile/processes.txt", group: "volatile:processes" }),
  a({ id: "lin.volatile.processes.cmdline", name: "Process command lines", category: "volatile", os: ["linux"], aliases: ["command line", "cmdline"],
    description: "Full arguments; may contain secrets.", sources: ["ps -eo pid,args"], acquisition: "snapshot", sensitivity: "sensitive-option", dependsOn: ["lin.volatile.processes"],
    output: "volatile/process-cmdlines.txt", group: "volatile:cmdline", selectAllExcluded: true }),
  a({ id: "lin.volatile.network", name: "Network connections", category: "volatile", os: ["linux"], aliases: ["ss", "netstat"],
    description: "Listening and established sockets.", sources: ["ss -anp (falls back to netstat -anp)"], acquisition: "snapshot", privilege: "elevated-recommended", output: "volatile/network.txt", group: "volatile:network",
    failureModes: ["Process names hidden without root", "Neither ss nor netstat installed"] }),
  a({ id: "lin.logs.journal", name: "systemd journal (bounded)", category: "logs", os: ["linux"], aliases: ["journalctl", "journald"],
    description: "journalctl export for the time window if systemd is present.", sources: ["journalctl --since <t> --until <t> -o export"], acquisition: "export", privilege: "elevated-recommended",
    timeFilter: "native", timeFilterNote: "Native --since/--until filtering.", failureModes: ["Non-systemd host", "Persistent journal absent"], output: "logs/journal.export", references: [LINUX_JOURNAL], group: "logs:system" }),
  a({ id: "lin.logs.auth", name: "Authentication logs", category: "logs", os: ["linux"], aliases: ["auth.log", "secure", "ssh logins"],
    description: "/var/log/auth.log (Debian family) or /var/log/secure (RHEL family) if present.", sources: ["/var/log/auth.log", "/var/log/secure"], privilege: "elevated-required", sensitivity: "moderate",
    timeFilter: "post-filter", timeFilterNote: "Whole file is copied; line time filtering is not applied in this version.", output: "logs/auth/", group: "logs:system" }),
  a({ id: "lin.logs.syslog", name: "General system logs", category: "logs", os: ["linux"], aliases: ["syslog", "messages"],
    description: "/var/log/syslog or /var/log/messages if present.", sources: ["/var/log/syslog", "/var/log/messages"], privilege: "elevated-recommended", output: "logs/syslog/", group: "logs:system" }),
  a({ id: "lin.scheduled.cron", name: "Cron configuration", category: "scheduled", os: ["linux"], aliases: ["crontab", "cron"],
    description: "/etc/crontab, /etc/cron.*, and user crontabs.", sources: ["/etc/crontab", "/etc/cron.d", "/etc/cron.{hourly,daily,weekly,monthly}", "/var/spool/cron"], privilege: "elevated-recommended", userScope: "per-user", output: "scheduled/cron/" }),
  a({ id: "lin.scheduled.timers", name: "systemd timers", category: "scheduled", os: ["linux"], aliases: ["timer", "systemctl list-timers"],
    description: "systemctl list-timers output and unit files for timers.", sources: ["systemctl list-timers --all", "/etc/systemd/system/*.timer (enumerated by collector)"], acquisition: "snapshot", failureModes: ["Non-systemd host"], output: "scheduled/timers.txt" }),
  a({ id: "lin.persistence.services", name: "Services & startup", category: "persistence", os: ["linux"], aliases: ["systemd units", "init.d", "rc.local"],
    description: "systemctl unit-file list, /etc/init.d and rc.local metadata; user unit directories.", sources: ["systemctl list-unit-files", "/etc/init.d", "/etc/rc.local", "<home>/.config/systemd/user", "<home>/.config/autostart"],
    userScope: "per-user", acquisition: "snapshot", failureModes: ["Non-systemd host"], output: "persistence/" }),
  a({ id: "lin.browser.chromium.history", name: "Chromium history & downloads", category: "browser", os: ["linux"], aliases: ["chrome history", "brave history", "downloads"],
    description: "History DB for Chrome/Chromium/Brave per user per profile.", sources: ["<home>/.config/google-chrome/<Profile>/History", "<home>/.config/chromium/<Profile>/History", "<home>/.config/BraveSoftware/Brave-Browser/<Profile>/History"],
    userScope: "per-user-profile", sensitivity: "personal-data", output: "browser/<user>/<browser>/<profile>/History", group: "browser:history", failureModes: ["Locked DB", "Snap/Flatpak paths differ and are not covered"] }),
  a({ id: "lin.browser.firefox.history", name: "Firefox history & downloads", category: "browser", os: ["linux"], aliases: ["firefox places"],
    description: "places.sqlite per profile.", sources: ["<home>/.mozilla/firefox/<name>/places.sqlite"], userScope: "per-user-profile", sensitivity: "personal-data",
    output: "browser/<user>/firefox/<profile>/places.sqlite", group: "browser:history", failureModes: ["Snap/Flatpak paths not covered"] }),
  a({ id: "lin.userlogs.user", name: "User application logs", category: "userlogs", os: ["linux"], aliases: ["~/.local/share logs", "xsession-errors"],
    description: "<home>/.xsession-errors and existing logs under <home>/.local/state (size bounded).", sources: ["<home>/.xsession-errors", "<home>/.local/state"], userScope: "per-user", sensitivity: "moderate", output: "userlogs/<user>/" }),
];

// Every OS also supports operator-supplied custom paths via plan.customPaths (see "custom" category).
